import type {Metadata} from "next";
import {Nunito} from "next/font/google";
import "./globals.css";
import {Header} from "@/components/shared";

const nunito = Nunito({subsets: ["cyrillic"]});

export const metadata: Metadata = {
    title: "Pizza app",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body className={nunito.className}>
        <main className='min-h-screen'>
            <Header/>
            {children}
        </main>
        </body>
        </html>
    );
}
