import React from 'react'

export const metadata = {
    title: 'Kasper Pizza | Доска',
    description: 'Generated by create next app',
};

export default function DashboardLayout({children}: { children: React.ReactNode }) {
    return (
        <main>
        <div>{children}</div>
        </main>
    );
}
